services:
  mysql:
    image: mysql:5.7
    restart: always
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: benchmark
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  app:
    build: .
    ports:
      - 3000:3000
    links:
      - mysql